function [fitresult, gof] = SRTM_fit_1(time, roi, reference)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Jul-2015 14:17:27


%% Fit: 'untitled fit 1'.
x = time;
y = roi;

[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'R1.*d_cerebellum(1,:) + k2.*cerebellum(2,:) - (k2./(1+BP)).*x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0.438744359656398 0.381558457093008 0.765516788149002 0.795199901137063 0.186872604554379];
opts.Upper = [Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on


