function [fitresult, gof] = createFit(Logan_x, Logan_y)
%CREATEFIT(LOGAN_X,LOGAN_Y)
%  Create a fit.
%
%  Data for 'Logan - better?' fit:
%      X Input : Logan_x
%      Y Output: Logan_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jan-2016 15:08:13


%% Fit: 'Logan - better?'.
[xData, yData] = prepareCurveData( Logan_x, Logan_y );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Logan - better?' );
h = plot( fitresult, xData, yData );
legend( h, 'Logan_y vs. Logan_x', 'Logan - better?', 'Location', 'NorthEast' );
% Label axes
xlabel Logan_x
ylabel Logan_y
grid on


